### PR TITLE
APIKEY - using them with 2.5 openweathermap API

### PR DESCRIPTION
**Pull request by jmoalves**
I introduced a simple solution to use ApiKeys with OpenWeatherMap.
Unfortunately, the current version (2.5) of the API **requires** the ApiKey :-(

### CODE REVIEW

**Comment by tylerbhughes** [comment]
@noazark can you look into why Travis CI isn't reporting it's status check? I don't think I have the ability to view it.

**Comment by noazark** [comment]
There was an outage on Travis CI that appears to have affected us. Try updating the test API key, or something else, to get travis to run again! The code looks good, and I know lots of people want this :D. Tyler, hit me up if you have any questions, but this has my 👍

**Comment by jmoalves** [comment]
Hurrah! Travis CI Build passed!

**Comment by tylerbhughes** [comment]
Thank you @jmoalves for your contribution!

**Comment by tylerbhughes** [comment]
@noazark can you add me as a contributor on NPM so that I can release a new version that contains this PR?

**Pull request merged**
